apiVersion: v1
kind: Namespace
metadata:
  name: '{{NAMESPACE}}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{APP_NAME}}'
  namespace: '{{NAMESPACE}}'
  labels:
    app: '{{APP_NAME}}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: '{{APP_NAME}}'
  template:
    metadata:
      labels:
        app: '{{APP_NAME}}'
    spec:
      containers:
      - name: '{{APP_NAME}}'
        image: snapshots.tomdoesdev/'{{APP_NAME}}':latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: '{{APP_NAME}}'
  namespace: '{{NAMESPACE}}'
  labels:
    app: '{{APP_NAME}}'
spec:
  ports:
  - name: '{{APP_NAME}}'
    port: 80
    targetPort: 80
  selector:
    app: '{{APP_NAME}}'
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: '{{APP_NAME}}'
  namespace: '{{NAMESPACE}}'
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: HostRegexp(`{{URL}}`, `{{SUBDOMAIN}}.{{URL}}`)
    services:
    - name: '{{APP_NAME}}'
      port: 80
